chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),

    path('<str:chatroom_pk>/', views.chatroom, name='chatroom'),

    path('new/<str:product_pk>/', views.new_chatroom, name='new-chatroom'),
]

myauth/urls.py
from django.urls import path, include, reverse_lazy

from django.contrib.auth import views as auth_views
from . import views

from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm

app_name = 'myauth'

urlpatterns = [
    path('signup/', views.signup, name='signup'),

    path('login/', auth_views.LoginView.as_view(
        template_name='myauth/login.html',
        authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='myauth/password_reset.html',
        email_template_name='myauth/password_reset_email.html',
        form_class=MyPasswordResetForm,
        success_url= reverse_lazy('myauth:password_reset_done')), name='password_reset'),

    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='myauth/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='myauth/password_reset_confirm.html',
        form_class=MySetPasswordForm,
        success_url = reverse_lazy('myauth:password_reset_complete')), name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='myauth/password_reset_complete.html'), name='password_reset_complete'),
]

shopmart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('myauth.urls')),
    path('products/', include('product.urls')),
    path('browse/', include('browse.urls')),
    path('payment/', include('payment.urls')),

    path('verification/', include('verify_email.urls')),

    path('chat/', include('chat.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myauth/models.py
from django.db import models

# Create your models here.

myauth/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django import forms


class MyPasswordResetForm(PasswordResetForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'w-full py-4 px-6 rounded-xl text-black'
    }))

class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={
        'placeholder': 'New password',
        'class': 'w-full py-4 px-6 rounded-xl text-black'
    }))

    new_password2 = forms.CharField(label='Repeat new password', widget=forms.PasswordInput(attrs={
        'placeholder': 'New password confirmation',
        'class': 'w-full py-4 px-6 rounded-xl text-black'
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl bg-cyan-900'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl bg-cyan-900'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl bg-cyan-900'
    }))

#    first_name = forms.CharField(widget=forms.TextInput(attrs={
#        'placeholder': 'Your first name',
#        'class': 'w-full py-4 px-6 rounded-xl'
#    }))

#    last_name = forms.CharField(widget=forms.TextInput(attrs={
#        'placeholder': 'Your last name',
#        'class': 'w-full py-4 px-6 rounded-xl'
#    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl bg-cyan-900'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl bg-cyan-900'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl bg-cyan-900'
    }))

myauth/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from verify_email.email_handler import send_verification_email

from .forms import SignupForm

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            inactive_user = send_verification_email(request, form=form)

            messages.success(request, 'Please check your email to activate your account!')
            
            return redirect('/')
        
    else:
        form = SignupForm()

    return render(request=request, template_name='myauth/signup.html', context={
        'title': 'SignUp',
        'form': form,
    })


myauth/templates/myauth/login.html
{% extends 'core/base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <!-- <div class="mb-3">
            <label class="inline-block mb-2">First Name</label><br>
            {{ form.first_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Last Name</label><br>
            {{ form.last_name }}
        </div> -->

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>


        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-300 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>  
        {% endif %}          
        <button class="py-1 px-6 my-5 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl transition duration-300 ease-in-out">Login</button>
        <p class="text-white">Forget Password?<a href="{% url 'myauth:password_reset' %}" class="text-blue-600 hover:text-blue-700">  Reset Password</a></p>
    </form>
</div>
{% endblock %}

myauth/templates/myauth/password_reset.html
{%extends 'core/base.html'%}

{% block title %} Password Reset {% endblock %}

{%block content%}
<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Reset Password</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {% for field in form %}
        <div class="mb-3">
            <label class="inline-block mb-2">{{ field.label_tag }}</label><br>
            {{ field }}
            {% if field.errors %}
	        	<small>{{ field.errors|striptags  }}</small> 
	        {% endif %}
        </div>
        {% endfor %}
        <input type="submit" value="Send" class="px-6 py-1 my-5 text-white font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition duration-300 ease-in-out">
        <a href="{%url 'myauth:login' %}"  class="px-6 py-2 my-5 text-white font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700 transition duration-300 ease-in-out">Cancel</a>
    </form>
</div>
{%endblock content%}

myauth/templates/myauth/password_reset_complete.html
{%extends 'core/base.html'%}

{% block title %} Reset Complete {% endblock %}

{%block content%}
<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Password Reset Complete</h1>
    <p>Your password has been reset, you can <a href="{% url 'myauth:login' %}" class="text-blue-600 hover:text-blue-700">  login to your account now</a></p>

</div>
{%endblock content%}

myauth/templates/myauth/password_reset_confirm.html
{%extends 'core/base.html'%}

{% block title %} New Password {% endblock %}

{%block content%}

<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
	<h2 class="mb-6 text-3xl text-center">Password Reset Confirm</h2>

	<form method="post" action=".">
	    {% csrf_token %}
	
	    {% for field in form %}
			<div class="mb-3">
	    		<label class="inline-block mb-2">{{ field.label_tag }}</label><br>
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
			</div>
		{% endfor %}
	  
	  <div>
	    <button type="submit" class="px-6 py-1 text-white font-semibold bg-teal-500 rounded-xl hover:bg-teal-700 transition duration-300 ease-in-out">Reset Password</button>
	  </div>
	</form>
</div>

{%endblock content%}

myauth/templates/myauth/password_reset_done.html
{%extends 'core/base.html'%}

{% block title %} Check Email {% endblock %}

{%block content%}
<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Password Reset</h1>
    <p>Please check your email and follow the instruction to reset your password.</p>

</div>
{%endblock content%}

myauth/templates/myauth/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'myauth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

myauth/templates/myauth/signup.html
{% extends 'core/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">{{ title }}</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <!-- <div class="mb-3">
            <label class="inline-block mb-2">First Name</label><br>
            {{ form.first_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Last Name</label><br>
            {{ form.last_name }}
        </div> -->

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-300 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>  
        {% endif %}          
        <button class="py-1 px-6 my-5 bg-teal-500 hover:bg-teal-700 rounded-xl transition duration-300 ease-in-out">SignUp</button>
    </form>
</div>
{% endblock %}