browse/urls.py
from django.urls import path
from . import views

app_name = 'browse'

urlpatterns = [
    path('', views.get_products, name='index'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),

    path('<str:chatroom_pk>/', views.chatroom, name='chatroom'),

    path('new/<str:product_pk>/', views.new_chatroom, name='new-chatroom'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('policy/', views.policy, name='policy'),
    path('terms/', views.terms, name='terms'),
]

myauth/urls.py
from django.urls import path, include, reverse_lazy

from django.contrib.auth import views as auth_views
from . import views

from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm

app_name = 'myauth'

urlpatterns = [
    path('signup/', views.signup, name='signup'),

    path('login/', auth_views.LoginView.as_view(
        template_name='myauth/login.html',
        authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='myauth/password_reset.html',
        email_template_name='myauth/password_reset_email.html',
        form_class=MyPasswordResetForm,
        success_url= reverse_lazy('myauth:password_reset_done')), name='password_reset'),

    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='myauth/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='myauth/password_reset_confirm.html',
        form_class=MySetPasswordForm,
        success_url = reverse_lazy('myauth:password_reset_complete')), name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='myauth/password_reset_complete.html'), name='password_reset_complete'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('new/', views.new_product, name='new'),
    path('<str:product_pk>/', views.product_detail, name='detail'),
    path('<str:product_pk>/edit/', views.edit_product, name='edit'),
    path('<str:product_pk>/delete/', views.product_delete, name='delete'),
]

shopmart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('myauth.urls')),
    path('products/', include('product.urls')),
    path('browse/', include('browse.urls')),
    path('payment/', include('payment.urls')),

    path('verification/', include('verify_email.urls')),

    path('chat/', include('chat.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.full_name}--{self.subject}--{self.message}'

core/forms.py
from django import forms

from .models import Contact

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border bg-cyan-950'

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('full_name', 'email', 'subject', 'message')
        widgets = {
            'full_name': forms.TextInput(attrs={
                'placeholder': 'Full Name*',
                'class': INPUT_CLASSES
            }),

            'email': forms.TextInput(attrs={
                'placeholder': 'Email Address*',
                'class': INPUT_CLASSES
            }),

            'subject': forms.TextInput(attrs={
                'placeholder': 'Subject*',
                'class': INPUT_CLASSES
            }),

            'message': forms.Textarea(attrs={
                'placeholder': 'Send a message...',
                'class': INPUT_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from product.models import Product, Category
from .forms import ContactForm

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        products_list = Product.objects.filter(is_sold=False).exclude(created_by=request.user).order_by('-created_at')
    else:
        products_list = Product.objects.filter(is_sold=False).order_by('-created_at')

    categories = Category.objects.all()

    paginator = Paginator(products_list, 5)

    page_number = request.GET.get('page', 1)
    products = paginator.get_page(page_number)

    return render(request=request, template_name='core/home/index.html', context={
        'title': 'Welcome',
        'products': products,
        'categories': categories,
    })

@login_required
def dashboard(request):
    products = Product.objects.filter(created_by = request.user)
    
    return render(request=request, template_name='core/home/dashboard.html', context={
        'products': products,
        'title': 'Dashboard'
    })

def about(request):
    return render(request=request, template_name='core/home/about.html', context={
        'title': 'About'
    })

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/')
        
    else:
        form = ContactForm()
        
    return render(request=request, template_name='core/home/contact.html', context={
        'form': form,
        'title': 'Contact'
    })

def policy(request):
    return render(request=request, template_name='core/home/policy.html', context={
        'title': 'Policy'
    })

def terms(request):
    return render(request=request, template_name='core/home/terms.html', context={
        'title': 'Terms'
    })


core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>

    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">

    {% block head %} {% endblock %}
    <title>{% block title %}{% endblock %} | ShopMart</title>

    {% block style %} {% endblock %}
</head>
<body class="bg-cyan-900 text-white">

    <nav id="short_navbar" class="lg:hidden flex flex-col justify-start items-center"> 

        <div class="mt-5 mx-8 px-6 py-3 w-4/5 rounded-full bg-cyan-950 flex justify-between items-center rounded-full bg-cyan-950 ">
            <button id="menu_icon" class="scale-125 hover:scale-150 transition duration-300 ease-in-out" onclick="toggleMenu()"><i class="ri-menu-line"></i></button>
            <a href="{% url 'core:index' %}" class="text-xl text-white font-semibold hover:scale-105 transition duration-300 ease-in-out">ShopMart</a>
        </div>    
        
        <div id="menu_list" class="absolute top-16 z-0 opacity-0 mt-5 mx-8 px-6 py-3 w-3/5 flex flex-col gap-5 items-center rounded-xl bg-cyan-950 shadow-lg transition-opacity duration-300 ease-in-out">
                <a href="{% url 'browse:index' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Browse</a>
                <!-- <a href="{% url 'request-new-link-from-email' %}" class="text-lg font-semibold hover:text-gray-500">Resend Email</a> -->

                {% if request.user.is_authenticated %}
                <a href="{% url 'product:new' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">List Item</a>
                <a href="{% url 'chat:inbox' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Inbox</a>
                <a href="{% url 'core:dashboard' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Dashboard</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                <a href="{% url 'myauth:logout' %}" class="w-32 text-center px-4 py-1 bg-red-500 text-white rounded-full hover:bg-red-700 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Logout</a>
                {% else %}
                <a href="{% url 'myauth:login' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">LogIn</a>
                <a href="{% url 'myauth:signup' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">SignUp</a>
                {% endif %}
    
        </div>
    </nav>

    <nav id="long_navbar" class="mt-5 mx-8 px-6 py-3 justify-between items-center rounded-full bg-cyan-950 hidden lg:flex shadow-lg">
        <div class="w-1/3 flex justify-start ">
            <a href="{% url 'core:index' %}" class="text-xl text-white font-semibold shadow-lg hover:scale-105 transition duration-300 ease-in-out">ShopMart</a>
        </div>

        <div class="w-1/3 whitespace-nowrap space-x-4 xl:space-x-8 flex justify-center">
            <a href="{% url 'browse:index' %}" class="{% if request.path == '/browse/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">Browse</a>
            <!-- <a href="{% url 'request-new-link-from-email' %}" class="text-lg font-semibold hover:text-gray-500">Resend Email</a> -->
            {% if request.user.is_authenticated %}
            <a href="{% url 'product:new' %}" class="{% if request.path == '/products/new/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 inline rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">List Item</a>
            <a href="{% url 'chat:inbox' %}" class="{% if request.path == '/chat/inbox/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">Inbox</a>
            <a href="{% url 'core:dashboard' %}" class="{% if request.path == '/dashboard/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">Dashboard</a>
            
            {% endif %}
        </div>

        <div class="w-1/3 space-x-4 flex justify-end">
            {% if request.user.is_authenticated %}
            <p class="inline-block flex items-center text-sm text-cyan-900">LoggedIn As {{ request.user.username|upper }}</p>
            <a href="{% url 'myauth:logout' %}" class="px-4 py-1 bg-red-500 text-white rounded-full hover:bg-red-700 shadow-lg transition duration-300 ease-in-out">Logout</a>
            {% else %}
            <a href="{% url 'myauth:login' %}" class="px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 shadow-lg transition duration-300 ease-in-out">LogIn</a>
            <a href="{% url 'myauth:signup' %}" class="px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 shadow-lg transition duration-300 ease-in-out">SignUp</a>
            {% endif %}
        </div>
    </nav>

    <main id="main_content" class="w-full sm:w-4/5 lg:max-w-7xl mx-auto p-6 transition-transform ease-in-out duration-300">
        {% if messages %}
        <div class="message mb-4 w-max mx-auto mt-4 px-10 py-2 text-center bg-slate-800 rounded-full shadow-2xl">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}

        {% block content %}

        {% endblock %}
    </main>

    <footer id="footer" class="px-6 py-6 flex justify-between border-gray-800 bg-cyan-950 transition-transform ease-in-out duration-300">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-300">About</h3>
            <p class="text-lg text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam facilis assumenda, optio eius rerum vel tempora provident quam! Officiis non repellendus tempora. Aliquid, officia nobis facilis consectetur delectus minus sed.</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-300">Menu</h3>
            <ul class="space-y-2">
                <li><a href=" {% url 'core:about' %} " class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href=" {% url 'core:contact' %} " class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href=" {% url 'core:policy' %} " class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href=" {% url 'core:terms' %} " class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>

    <script>
        function toggleMenu () {
            var menuIconElement = document.getElementById('menu_list');
            var mainContentElement = document.getElementById('main_content');
            var footerElement = document.getElementById('footer');

            if (menuIconElement.classList.contains('opacity-0')) {
                menuIconElement.classList.remove('opacity-0');
                menuIconElement.classList.add('opacity-100');
            } else {
                menuIconElement.classList.add('opacity-0');
                menuIconElement.classList.remove('opacity-100')
            }

            mainContentElement.classList.toggle('translate-y-72'); // Push down
            footerElement.classList.toggle('translate-y-72')
            
        }
    </script>

    {% block scripts %}

    {% endblock %}

</body>
</html>