chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),

    path('<str:chatroom_pk>/', views.chatroom, name='chatroom'),

    path('new/<str:product_pk>/', views.new_chatroom, name='new-chatroom'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('new/', views.new_product, name='new'),
    path('<str:product_pk>/', views.product_detail, name='detail'),
    path('<str:product_pk>/edit/', views.edit_product, name='edit'),
    path('<str:product_pk>/delete/', views.product_delete, name='delete'),
]

shopmart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('myauth.urls')),
    path('products/', include('product.urls')),
    path('browse/', include('browse.urls')),
    path('payment/', include('payment.urls')),

    path('verification/', include('verify_email.urls')),

    path('chat/', include('chat.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

product/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User

from datetime import timedelta
from django.utils import timezone

import uuid

# Create your models here.

class Category(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    name = models.CharField(max_length=191)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    
class Product(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=191)
    price = models.FloatField()

    created_by = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    
    description = models.TextField( blank=True, null=True )
    image = models.ImageField(upload_to= 'product_images', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    is_sold = models.BooleanField(default=False)
    is_reserved = models.BooleanField(default=False)
    reserved_at = models.DateTimeField(null=True, blank=True)
    reservation_duration = timedelta(minutes=1)
    reserved_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    def reserve(self, user):
        self.is_reserved = True
        self.reserved_by = user
        self.reserved_at = timezone.now()
        self.save()

    def unreserve(self):
        self.is_reserved = False
        self.reserved_by = None
        self.reserved_at = None
        self.save()

    def is_reservation_expired(self):
        if self.is_reserved:
            if timezone.now() > self.reserved_at + self.reservation_duration:
                return True
            else:
                return False
        else:
            return True

    def __str__(self):
        return f'{self.name}--{self.created_by.username}'


product/forms.py
from django import forms
from .models import Product

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl bg-cyan-900'

class NewProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Product
from .forms import NewProductForm,  EditProductForm

# Create your views here.
def product_detail(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    related_products = Product.objects.filter(is_sold=False).filter(is_reserved=False).filter(category=product.category).exclude(pk=product_pk)

    if not product.is_sold:
        if product.is_reserved:
            if product.is_reservation_expired():
                print('Product in unreserved')
                product.unreserve()
                product.save()

    return render(request=request, template_name='product/detail.html', context={
        'product': product,
        'related_products': related_products
    })

@login_required
def new_product(request):
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)

        if form.is_valid():
            product_new = form.save(commit=False)
            product_new.created_by = request.user
            product_new.save()

            return redirect('product:detail', product_new.id)
    
    else:
        form = NewProductForm()

    return render(request=request, template_name='product/product_form.html', context={
        'form': form,
        'title': 'List New Product'
    })

@login_required
def edit_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)

    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)
        
        if form.is_valid():
            form.save()
            return redirect('product:detail', product.id)
        
    else:
        form = EditProductForm(instance=product)

    return render(request=request, template_name='product/product_form.html', context={
        'form': form,
        'title': 'Edit Your product'
    })
        
@login_required
def product_delete(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    product.delete()
    return redirect('core:dashboard')

product/templates/product/detail.html
{% extends 'core/base.html' %}

{% load static %} <!-- payment -->

{% block title %} {{ product.name }} {% endblock %}

{% block head %}
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'payment/stripe.js' %}"></script>   <!-- new -->
{% endblock %}

{% block content %}
    <div class="flex flex-col md:flex-row gap-5 justify-evenly">

        {% if product.image %}
        <div class="w-full h-[600px] md:w-3/5 rounded-xl overflow-hidden border-8 border-cyan-950"> 
            <img src="{{ product.image.url }}" class="w-full h-full object-cover">
        </div>
        {% else %}
        <div class="w-full h-[600px] md:w-3/5 rounded-xl overflow-hidden border-8 border-cyan-950"> 
            <h1 class="w-full h-full flex justify-center items-center text-gray-300">No image available</h1>
        </div>
        {% endif %}

        <div class="w-full md:w-2/5 p-6 bg-cyan-950 rounded-xl">
            <h1 class="mb-6 text-3xl font-bold text-cyan-500">{{ product.name }}</h1>
            <p class="text-gray-300 text-xl font-semibold">Price: ${{ product.price }}</p>
            <p class="text-gray-300 text-lg font-semibold">Seller: {{ product.created_by.username }}</p>

        {% if product.description %}
            <p class="text-gray-500">Description: {{ product.description }}<strong class="text-gray-500"></strong></p>
        {% endif %}
        {% if product.is_sold %}
            <p class="text-3xl font-bold text-gray-500">SOLD</p>
        {% endif %}
        {% if product.is_reserved %}
            <p class="text-gray-700"><strong class="text-gray-500">This product is reserved and awaiting for payment.</strong></p>
        {% endif %}

        {% if request.user.is_authenticated %}

        {% if product.created_by == request.user %}
            <a href="{% url 'product:edit' product.id %}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition duration-300 ease-in-out">Edit</a>
            <a href="{% url 'product:delete' product.id %}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700 transition duration-300 ease-in-out">Delete</a>
        {% else %}
            <a href="{% url 'chat:new-chatroom' product.id %}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition duration-300 ease-in-out">Contact Seller</a>
            <button id="submitBtn" product-pk="{{product.id}}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700 transition duration-300 ease-in-out {% if product.is_sold or product.is_reserved %} bg-gray-400 pointer-events-none {% endif %}">Purchase</button>
        {% endif %}

        {% else %}
            <h1 class="mt-5 text-xl font-bold text-cyan-500">Please log in to edit, delete and purchase product!!</h1>
        {% endif %}
        </div>
    </div>

    <div class="mt-6 px-5 py-12 bg-cyan-950 rounded-xl">
        <h2 class="mb-12 text-3xl font-semibold text-center">Related products</h2>
        <div class="flex flex-col md:flex-row md:flex-wrap gap-5 justify-evenly items-center">
            {% for product in related_products %}
                    <a href="{% url 'product:detail' product.id %}" class="w-96 hover:scale-105 transition duration-300 ease-in-out">
                        <div class="w-full h-80 rounded-t-xl overflow-hidden">
                            <img src="{{ product.image.url }}" alt="product-image" class="w-full h-full object-cover">
                        </div>
                        <div class="p-6 bg-cyan-900 rounded-b-xl">
                            <h2 class="text-2xl font-semibold text-cyan-500">{{ product.name }}</h2>
                            <p class="text-black">${{ product.price }}</p>
                        </div>
                    </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

product/templates/product/product_form.html
{% extends 'core/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
			<div class="mb-3">
	    		<label class="inline-block mb-2">{{ field.label_tag }}</label><br>
	        	{{ field }}
			</div>
		{% endfor %}

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>  
        {% endif %}          
        <button class="py-1 px-6 mt-5 bg-teal-500 hover:bg-teal-700 rounded-xl transition duration-300 ease-in-out">List</button>
    </form>
</div>
{% endblock %}